version: "3.8"

services:
  web:
    build: .
    image: sih-url-detector:latest
    ports:
      - "8000:5000"
    volumes:
      - ./uploads:/app/uploads # persist uploaded PCAPs/logs
      - ./templates:/app/templates # hot-reload templates during dev
      - ./static:/app/static
      - .:/app
      - ./data:/app/data # hot-reload static assets
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - TSHARK_PATH=/usr/bin/tshark
    restart: unless-stopped
